[package]
name = "fractolrs"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24.8"
chrono = "0.4.34"
num-complex = "0.4.5"
rayon = "1.8.1"
eframe = "0.26.2"
egui = "0.26.2"
parking_lot = "0.12.1"
bytemuck = "1.14.3"
num_cpus = "1.16.0"
rand = "0.8.5"
